package com.fcm.authzcraft.api.plan;

public enum FailureCode {
    REQUEST_INVALID,
    SUBJECT_UNAVAILABLE,
    ATTRIBUTE_MISSING,
    SOURCE_STALE,
    UNTRUSTED_CONTEXT,
    PIP_UNAVAILABLE,
    PDP_UNAVAILABLE,
    RESOURCE_UNAVAILABLE,
    POLICY_UNAVAILABLE,
    GRANT_ARGUMENT_INVALID,
    CATALOG_DRIFT,
    ACCESS_PATH_UNAVAILABLE,
    PLAN_EXPIRED,
    PLAN_INVALID,
    SQL_UNSUPPORTED,
    INTERNAL_ERROR
}